apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: sintesi-classi-errore-versamenti-falliti
  template: sintesi-classi-errore-versamenti-falliti-quarkus
metadata:
  annotations:
    description: |-
      Template microservizio sintesi classi errore versamenti falliti (vedere https://gitlab.ente.regione.emr.it/parer/okd/sintesi-classi-errore-versamenti-falliti.git)
    iconClass: icon-quarkus
    openshift.io/display-name: Microservice sintesi classi errore versamenti falliti
    openshift.io/documentation-url: https://gitlab.ente.regione.emr.it/parer/okd/sintesi-classi-errore-versamenti-falliti
    openshift.io/long-description: Il template fornisce la creazione del microservizio sintesi classi errore versamenti falliti
    openshift.io/provider-display-name: Parer (Regione Emilia Romagna)
    openshift.io/support-url: https://gitlab.ente.regione.emr.it/parer
    tags: quarkus
    template.openshift.io/bindable: "false"
  name: sintesi-classi-errore-versamenti-falliti-quarkus
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: sintesi-classi-errore-versamenti-falliti-secrets 
    labels:
      app: sintesi-classi-errore-versamenti-falliti    
  stringData:
    QUARKUS_OIDC_CLIENT_ID: ${CLIENT_ID}
    QUARKUS_OIDC_CREDENTIALS_CLIENT_SECRET_VALUE: ${CLIENT_SECRET}
    QUARKUS_OIDC_AUTH_SERVER_URL: ${AUTH_SERVER_URL}
    QUARKUS_OIDC_INTROSPECTION_PATH: ${INTROSPECTION_PATH}
    QUARKUS_DATASOURCE_JDBC_URL: ${DATABASE_URL}
    QUARKUS_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    QUARKUS_DATASOURCE_USERNAME: ${DATABASE_USER}
  type: Opaque
- apiVersion: v1
  kind: Secret
  data:
    .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5lbnRlLnJlZ2lvbmUuZW1yLml0L3BhcmVyLyI6eyJ1c2VybmFtZSI6Im9rZF9kZXBsb3kiLCJwYXNzd29yZCI6IlhUWkJ5V1lBQnZ4UVVMOFdreHFxIiwiZW1haWwiOiJnaXRsYWJAZGVwbG95LmxvY2FsIn19fQ==
  metadata:
    name: gitlab-registry-token
  type: kubernetes.io/dockerconfigjson
- apiVersion: v1
  kind: ConfigMap
  data:
    application.yaml: |-
      "%${PROFILE}":
        quarkus:
          #(locked build time)
          #ssl:
          #native: "true"
          http:
            port: 8080
            test-port: 0
          shutdown:
            timeout: "PT30S"
          datasource:
            db-kind: "oracle"
            jdbc:
              driver: "oracle.jdbc.driver.OracleDriver"
          hibernate-orm:
            database:
              generation: "none"
          security:
            users:
              embedded:
                #plain-text: true
                users:
                  admin: "db0df53c9894a31b7defe5489028f236"
                roles: 
                  admin: "admin"            
          #logging
          log:
            level: INFO
            console:
              json: false
              format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %X{log_uuid} %s%E%n"
            category:
              it.eng.parer.classierrore:
                level: "INFO"
        # custom logger (single line throw)
        parer:
          quarkus:
            config:
              singleline-message:
                enabled: true
  metadata:
    labels:
      app: sintesi-classi-errore-versamenti-falliti
    name: sintesi-classi-errore-versamenti-falliti-config
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: sintesi-classi-errore-versamenti-falliti
      expose: "true"
    name: sintesi-classi-errore-versamenti-falliti
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: sintesi-classi-errore-versamenti-falliti
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 10m
    labels:
      app: sintesi-classi-errore-versamenti-falliti
      expose: "true"
    name: sintesi-classi-errore-versamenti-falliti
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: sintesi-classi-errore-versamenti-falliti
      weight: 100
    wildcardPolicy: None
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: sintesi-classi-errore-versamenti-falliti
      gl_log_application: sintesi-classi-errore-versamenti-falliti
      gl_tags: ${AMBIENTE}
      group: it.eng.parer
    name: sintesi-classi-errore-versamenti-falliti
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: sintesi-classi-errore-versamenti-falliti
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
      resources:
        limits:
          cpu: 20m
          memory: 50Mi        
        requests:
          cpu: 10m
          memory: 40Mi
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: sintesi-classi-errore-versamenti-falliti
          gl_log_application: sintesi-classi-errore-versamenti-falliti
          gl_tags: ${AMBIENTE}
          group: it.eng.parer
      spec:
        containers:
        - env:
          - name: QUARKUS_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                key:  QUARKUS_DATASOURCE_USERNAME
                name: sintesi-classi-errore-versamenti-falliti-secrets
          - name: QUARKUS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: QUARKUS_DATASOURCE_PASSWORD
                name: sintesi-classi-errore-versamenti-falliti-secrets
          - name: JAVA_OPTS_APPEND
            value: -Dfile.encoding=UTF-8 -Dquarkus.profile=${PROFILE}  -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -Dsun.zip.disableMemoryMapping=true -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3000 -Dcom.sun.management.jmxremote.rmi.port=3001 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
          - name: JAVA_MAX_MEM_RATIO
            value: "90"
          - name: JAVA_INITIAL_MEM_RATIO
            value: "40"
          - name: TZ
            value: Europe/Rome
          - name: QUARKUS_OIDC_CREDENTIALS_CLIENT_SECRET_VALUE
            valueFrom:
              secretKeyRef:
                key: QUARKUS_OIDC_CREDENTIALS_CLIENT_SECRET_VALUE
                name: sintesi-classi-errore-versamenti-falliti-secrets
          - name: QUARKUS_OIDC_AUTH_SERVER_URL
            valueFrom:
              secretKeyRef:
                key: QUARKUS_OIDC_AUTH_SERVER_URL
                name: sintesi-classi-errore-versamenti-falliti-secrets
          - name: QUARKUS_OIDC_INTROSPECTION_PATH
            valueFrom:
              secretKeyRef:
                key: QUARKUS_OIDC_INTROSPECTION_PATH
                name: sintesi-classi-errore-versamenti-falliti-secrets                
          - name: QUARKUS_OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: QUARKUS_OIDC_CLIENT_ID
                name: sintesi-classi-errore-versamenti-falliti-secrets
          - name: QUARKUS_DATASOURCE_JDBC_URL
            valueFrom:
              secretKeyRef:
                key:  QUARKUS_DATASOURCE_JDBC_URL
                name: sintesi-classi-errore-versamenti-falliti-secrets
          image: registry.ente.regione.emr.it/parer/okd/sintesi-classi-errore-versamenti-falliti:${IMGTAG}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 180
          name: sintesi-classi-errore-versamenti-falliti
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 180
          resources:
            limits:
              cpu: 800m
              memory: 2000Mi
            requests:
              cpu: 400m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /deployments/config
            name: sintesi-classi-errore-versamenti-falliti-config
            readOnly: true
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: gitlab-registry-token
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext:
          runAsUser: 1000660000
          fsGroup: 1000660000        
        volumes:
        - configMap:
            defaultMode: 420
            name: sintesi-classi-errore-versamenti-falliti-config
          name: sintesi-classi-errore-versamenti-falliti-config
    test: false
    triggers:
    - type: ConfigChange
parameters:
- description: Nome dal tag dell'immagine da utilizzare (default latest)
  displayName: Nome immagine
  name: IMGTAG
  required: false
  value: latest
- description: Nome dell'ambiente o namespace (e.g. latest/stable/pre-prod/prod)
  displayName: ambiente
  name: AMBIENTE
  required: false
  value: latest
- description: Nome profilo quarkus
  displayName: Nome profilo quarkus
  name: PROFILE
  required: true  
- description: Client id (configurato su WSO2 / Keycloack per autenticazione OIDC/OAUTH2)
  displayName: Client id
  name: CLIENT_ID
  required: false
  value: parer-api  
- description: Client secrets (configurato su WSO2 / Keycloack per autenticazione OIDC/OAUTH2)
  displayName: Client secrets
  name: CLIENT_SECRET
  required: true
- description: Host servizio di introspection token (Keycloack e.g. https://sso-parer-test.regione.emilia-romagna.it/auth/realms/Parer)
  displayName: Host servizio di introspection token
  name: AUTH_SERVER_URL
  required: true
- description: Introspect path per servizio di introspection token (Keycloack e.g. /protocol/openid-connect/token/introspect)
  displayName: Introspect path per servizio di introspection token
  name: INTROSPECTION_PATH
  required: false
  value: /protocol/openid-connect/token/introspect    
- description: URL per accesso db
  displayName: URL per accesso db
  name: DATABASE_URL
  required: true  
- description: Nome utente per accesso db
  displayName: Nome utente per accesso db
  name: DATABASE_USER
  required: true
- description: Password per accesso db
  displayName: Password per accesso db
  name: DATABASE_PASSWORD
  required: true